services:
    php:
        build: .docker/php
        ports:
            - "5173:5173"
        volumes:
            - .:/var/www:cached

    nginx:
        image: nginx
        ports:
            - "80:80"
        volumes:
            - .:/var/www
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php

    db:
        image: mysql:8.1
        ports:
            - "3306:3306"
        volumes:
            - .docker/db/data:/var/lib/mysql
            - .docker/logs:/var/log/mysql
            - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: workmaster_planner
            MYSQL_USER: workmaster
            MYSQL_PASSWORD: workmaster
